
development:
  adapter: postgresql
  encoding: unicode
  database: sebastian_rusu
  pool: 5
  username: sebastian_rusu
  password: karynutza
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: sebastian_rusu
  pool: 5
  username: sebastian_rusu
  password: karynutza
  timeout: 5000
  host: localhost
